# Strict Flutter Linting Configuration
# This configuration provides comprehensive linting rules for maintaining
# high code quality, performance, and consistency in Flutter projects.

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated/**"
    - "**/l10n/**"
    - "**/*.config.dart"

  errors:
    # Treat as errors
    missing_required_param: error
    missing_return: error
    dead_code: error
    unused_import: error
    unused_local_variable: error

    # Treat as warnings
    deprecated_member_use: warning

    # Ignore
    invalid_annotation_target: ignore
    todo: ignore # Change to 'warning' if you want to track TODOs

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # BASE RULES (from flutter_lints)
    # These are already included but listed for reference

    # Code Organization & Imports
    - always_use_package_imports
    - directives_ordering
    - always_declare_return_types
    - eol_at_end_of_file

    # Error Prevention
    - avoid_print
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - no_logic_in_create_state
    - use_build_context_synchronously
    - avoid_slow_async_io
    - avoid_returning_null_for_void
    - parameter_assignments
    - test_types_in_equals

    # Performance & Optimization
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_colored_box
    - use_decorated_box
    - unnecessary_await_in_return
    - prefer_foreach

    # Const & Immutability
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals

    # Code Simplification
    - avoid_bool_literals_in_conditional_expressions
    - avoid_redundant_argument_values
    - avoid_types_on_closure_parameters
    - prefer_expression_function_bodies
    - prefer_if_null_operators
    - prefer_null_aware_operators
    - use_if_null_to_convert_nulls_to_bools
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_string_interpolations

    # Code Style & Formatting
    - always_put_control_body_on_new_line
    - leading_newlines_in_multiline_strings
    - require_trailing_commas
    - sort_child_properties_last
    # - lines_longer_than_80_chars  # Uncomment if you want to enforce line length

    # Flutter Best Practices
    - use_key_in_widget_constructors
    - use_full_hex_values_for_flutter_colors
    - sized_box_shrink_expand
    - avoid_returning_widgets

    # Modern Dart Features
    - use_super_parameters
    - use_enums
    - use_named_constants

    # Additional Quality Rules
    - avoid_double_and_int_checks
