// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3fyGezIxkXT8WTb_lYOnp7-mu0iJBfGA',
    appId: '1:502150476162:android:f5a7f91d3359be94ac5f9b',
    messagingSenderId: '502150476162',
    projectId: 'movify-dev',
    storageBucket: 'movify-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-FUx-C1BmexDT2iTXdZrG4mvfvbU93S0',
    appId: '1:502150476162:ios:4fd1f46f1178f363ac5f9b',
    messagingSenderId: '502150476162',
    projectId: 'movify-dev',
    storageBucket: 'movify-dev.firebasestorage.app',
    androidClientId: '502150476162-he9n9nvj2c286omsv83osc1ph5hkqf4t.apps.googleusercontent.com',
    iosClientId: '502150476162-lo62dhh3c4fgeve8c5rmnfnomlt5epj8.apps.googleusercontent.com',
    iosBundleId: 'com.rami.movify',
  );

}