// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsDev.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsDev are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC061ueY01V-dyxQoMTju0jwJTGIssUSJE',
    appId: '1:59698721964:web:53b2c51c4949e8aa7b1b09',
    messagingSenderId: '59698721964',
    projectId: 'movify-dev-project',
    authDomain: 'movify-dev-project.firebaseapp.com',
    storageBucket: 'movify-dev-project.firebasestorage.app',
    measurementId: 'G-XK3NBKR3SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx3wkOq3F-93KN-Gg_mSj3YIYH6SxFwxs',
    appId: '1:59698721964:android:4e51d251dcb212417b1b09',
    messagingSenderId: '59698721964',
    projectId: 'movify-dev-project',
    storageBucket: 'movify-dev-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrZDbLuKKvW6TWhJTUcnghSb_hV6H9L7Y',
    appId: '1:59698721964:ios:29c090f848df479d7b1b09',
    messagingSenderId: '59698721964',
    projectId: 'movify-dev-project',
    storageBucket: 'movify-dev-project.firebasestorage.app',
    iosBundleId: 'com.example.cinemaxAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrZDbLuKKvW6TWhJTUcnghSb_hV6H9L7Y',
    appId: '1:59698721964:ios:29c090f848df479d7b1b09',
    messagingSenderId: '59698721964',
    projectId: 'movify-dev-project',
    storageBucket: 'movify-dev-project.firebasestorage.app',
    iosBundleId: 'com.example.cinemaxAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC061ueY01V-dyxQoMTju0jwJTGIssUSJE',
    appId: '1:59698721964:web:66a4e3cfa07a09d17b1b09',
    messagingSenderId: '59698721964',
    projectId: 'movify-dev-project',
    authDomain: 'movify-dev-project.firebaseapp.com',
    storageBucket: 'movify-dev-project.firebasestorage.app',
    measurementId: 'G-2KVS9V1V09',
  );
}
