// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8yzuEiuWRo7-bmt-_Fx7LT1ZC7F5h4HI',
    appId: '1:510131261228:web:2184e9303345e11c4c6689',
    messagingSenderId: '510131261228',
    projectId: 'cinemamaxapp-be698',
    authDomain: 'cinemamaxapp-be698.firebaseapp.com',
    storageBucket: 'cinemamaxapp-be698.firebasestorage.app',
    measurementId: 'G-VG01DK2JKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuosLn4dJtNxTCjDGcpFnkjJuz96FdCM4',
    appId: '1:510131261228:android:5c79e851aa9b126a4c6689',
    messagingSenderId: '510131261228',
    projectId: 'cinemamaxapp-be698',
    storageBucket: 'cinemamaxapp-be698.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyr7UNajUylMVoogZd8AevkXxr-ZzcAWQ',
    appId: '1:510131261228:ios:6b37cdc7c9f296014c6689',
    messagingSenderId: '510131261228',
    projectId: 'cinemamaxapp-be698',
    storageBucket: 'cinemamaxapp-be698.firebasestorage.app',
    androidClientId: '510131261228-2d0otuq9neknln573m4g4dj65pr5uj9r.apps.googleusercontent.com',
    iosClientId: '510131261228-a7r94617adt9ke1h2ifa4r8lkmsstvsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemaxAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyr7UNajUylMVoogZd8AevkXxr-ZzcAWQ',
    appId: '1:510131261228:ios:6b37cdc7c9f296014c6689',
    messagingSenderId: '510131261228',
    projectId: 'cinemamaxapp-be698',
    storageBucket: 'cinemamaxapp-be698.firebasestorage.app',
    androidClientId: '510131261228-2d0otuq9neknln573m4g4dj65pr5uj9r.apps.googleusercontent.com',
    iosClientId: '510131261228-a7r94617adt9ke1h2ifa4r8lkmsstvsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemaxAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1GzwJH3w0nv-1h-kW3twGlQ7SNz7b3LA',
    appId: '1:510131261228:web:ecee64cc18c607bd4c6689',
    messagingSenderId: '510131261228',
    projectId: 'cinemamaxapp-be698',
    authDomain: 'cinemamaxapp-be698.firebaseapp.com',
    storageBucket: 'cinemamaxapp-be698.firebasestorage.app',
    measurementId: 'G-BTYZLZKR7V',
  );

}