// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyhcjaKCDJO_qg2UnrJyymSz5qLGJJihU',
    appId: '1:322470183826:android:fb5eb7517bc9dde1e5774b',
    messagingSenderId: '322470183826',
    projectId: 'movify-prod',
    storageBucket: 'movify-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_yoi4RnoezubsF1j6QXmGIdciW-4VZeg',
    appId: '1:322470183826:ios:19c9c4c070c2a080e5774b',
    messagingSenderId: '322470183826',
    projectId: 'movify-prod',
    storageBucket: 'movify-prod.firebasestorage.app',
    androidClientId: '322470183826-g55pvg4tua0qqag5nlc7f8mla1fu7har.apps.googleusercontent.com',
    iosClientId: '322470183826-r67ipldo9g5dktrb19q4iemd8i57tu57.apps.googleusercontent.com',
    iosBundleId: 'com.rami.movify',
  );
}
