# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  
  desc "Build Dev Flavor and upload to Firebase App Distribution"
  lane :distribute_dev do
    
    # 1. Go to the project root and build the Flutter APK
    #    Fastlane runs from android/fastlane/, so ../.. = project root
    Dir.chdir("../..") do
      UI.message("🔨 Building Dev APK with Shorebird...")
      sh("shorebird release android --flavor dev -t lib/main_dev.dart --artifact apk --split-per-abi --obfuscate --split-debug-info=build/app/outputs/symbols")

      # 1. Grab the exact, absolute path while we are safely in the project root!
      absolute_apk_path = File.expand_path("build/app/outputs/flutter-apk/app-arm64-v8a-dev-release.apk")
      # 2. Upload the finished APK to Firebase
      firebase_app_distribution(
        app: ENV["FIREBASE_DEV_APP_ID"],
        groups: "testers",
        release_notes: "New Dev Build from CI/CD 🚀",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        apk_path: absolute_apk_path
      )
    end
  end

  desc "Build Prod Flavor and upload to Firebase App Distribution"
  lane :distribute_prod do
    
    Dir.chdir("../..") do
      UI.message("🔨 Building Prod APK...")
      sh("flutter build apk --flavor prod -t lib/main_prod.dart  --split-per-abi --obfuscate --split-debug-info=build/app/outputs/symbols")

      firebase_app_distribution(
        app: ENV["FIREBASE_PROD_APP_ID"],
        groups: "testers",
        release_notes: "New Prod Build from CI/CD 🚀",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        apk_path: "build/app/outputs/flutter-apk/app-arm64-v8a-prod-release.apk"
      )
    end
  end

end
